#!/bin/bash

# Criar itens
    # Prato
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H 'Content-Type: application/json' -d '{
        "descricao":"Coxinha",
        "valor":"5.99",
        "tipo":"prato"
    }'
    # Bebida
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{
        "descricao":"Champanhe",
        "valor":"99.99",
        "tipo":"bebida"
    }'
    # Sobremesa
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{
        "descricao":"Brigadeiro",
        "valor":"3.99",
        "tipo":"prato"
    }'
    # Prato
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{
        "descricao":"Feijoada",
        "valor":"12.99",
        "tipo":"prato"
    }'

# Abrir comandas
    curl -X POST "http://localhost/restaurante/back/api/comanda.php" # Comanda 1
    curl -X POST "http://localhost/restaurante/back/api/comanda.php" # Comanda 2
    curl -X POST "http://localhost/restaurante/back/api/comanda.php" # Comanda 3

# Criar itens das comandas
    # Comanda 1
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"1",
        "id_item":"1",
        "quantidade":"2"
    }'
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"1",
        "id_item":"2",
        "quantidade":"1"
    }'
    
    # Comanda 2
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"2",
        "id_item":"3",
        "quantidade":"3"
    }'
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"2",
        "id_item":"4",
        "quantidade":"1"
    }'

    # Comanda 3
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"3",
        "id_item":"1",
        "quantidade":"1"
    }'
    curl -X POST "http://localhost/restaurante/back/api/itemcomanda.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"3",
        "id_item":"4",
        "quantidade":"2"
    }'

# Fechar comandas
    curl -X PUT "http://localhost/restaurante/back/api/comanda.php" -H 'Content-type: application/json' -d '{
        "id": "1"
    }'
    curl -X PUT "http://localhost/restaurante/back/api/comanda.php" -H 'Content-type: application/json' -d '{
        "id": "2"
    }'
    curl -X PUT "http://localhost/restaurante/back/api/comanda.php" -H 'Content-type: application/json' -d '{
        "id": "3"
    }'

# Pagamento das comandas
    curl -X POST "http://localhost/restaurante/back/api/pagamento.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"1",
        "forma_pagamento":"pix",
        "valor":"111.97"
    }'
    curl -X POST "http://localhost/restaurante/back/api/pagamento.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"2",
        "forma_pagamento":"debito",
        "valor":"24.96"
    }'
    curl -X POST "http://localhost/restaurante/back/api/pagamento.php" -H "Content-Type: application/json" -d '{
        "id_comanda":"3",
        "forma_pagamento":"credito",
        "valor":"31.97"
    }'