#!/bin/bash
## CRIAR
    # Testar POST (Criar) - Válido
    curl -X POST "http://localhost/restaurante/back/api/comanda.php"
    
    # Testar POST (Criar) - Válido com token
    curl -X POST "http://localhost/restaurante/back/api/comanda.php" -H 'Content-type: application/json' -d '{
        "token": "c5fe6e39f403038bbb39a3d7ea6b6cdcfa7eceb831d522b10cbad7f8ca39e8fe"
    }'

## LER

    # Testar GET All
    curl -X GET "http://localhost/restaurante/back/api/comanda.php"

    # Testar GET com ID = Válido
    curl -X GET "http://localhost/restaurante/back/api/comanda.php?id=2"

    # Testar GET com ID = Inválido
    curl -X GET "http://localhost/restaurante/back/api/comanda.php?id=99"

## EDITAR

    # Testar PUT (Editar) - Válido
    #Fecha comanda
    curl -X PUT "http://localhost/restaurante/back/api/comanda.php"  -H 'Content-type: application/json' -d '{
        "id": "3"
    }'

## DELETAR

    # Testar Deleção - Válido
    curl -X DELETE "http://localhost/restaurante/back/api/comanda.php?id=4"

    # Testar Deleção - Inválido
    curl -X DELETE "http://localhost/restaurante/back/api/comanda.php?id=10"

    # Testar deleção sem parâmetro
    curl -X DELETE "http://localhost/restaurante/back/api/comanda.php"