#!/bin/bash
## CRIAR
    # Testar POST (Criar) - Válido
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{
        "descricao":"Coxinha",
        "valor":"5.99",
        "tipo":"prato"
    }'

    # Testar POST (Criar) - Inválido
    curl -X POST "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{
        "descricao":"",
        "valor":"5,78"
    }'

## LER

    # Testar GET All
    curl -X GET "http://localhost/restaurante/back/api/item.php"

    # Testar GET com ID = Válido
    curl -X GET "http://localhost/restaurante/back/api/item.php?id=3"

    # Testar GET com ID = Inválido
    curl -X GET "http://localhost/restaurante/back/api/item.php?id=99"

## EDITAR

    # Testar PUT (Atualizar) - Válido
    curl -X PUT "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{"id":3,"descricao":"Teste de edicao"}'

    # Testar PUT (Atualizar) - Inválido
    curl -X PUT "http://localhost/restaurante/back/api/item.php" -H "Content-Type: application/json" -d '{"descricao":"Teste Atualizado"}'

## DELETAR

    # Testar Deleção - Válido
    curl -X DELETE "http://localhost/restaurante/back/api/item.php?id=3"

    # Testar Deleção - Inválido
    curl -X DELETE "http://localhost/restaurante/back/api/item.php?id=10"

    # Testar deleção sem parâmetro
    curl -X DELETE "http://localhost/restaurante/back/api/item.php"