#!/bin/bash

# Todos os relatorios
curl -X GET "http://localhost/restaurante/back/api/relatorios.php"

# Ordens Cozinha
curl -X GET "http://localhost/restaurante/back/api/relatorios.php?view=ordens_producao_cozinha"

# Ordens copa
curl -X GET "http://localhost/restaurante/back/api/relatorios.php?view=ordens_producao_copa"

# Todas as ordens
curl -X GET "http://localhost/restaurante/back/api/relatorios.php?view=ordens_producao"

# Relatorio do dia
curl -X GET "http://localhost/restaurante/back/api/relatorios.php?view=vendas_do_dia"