#!/bin/bash
## CRIAR
    
    # Criar usuário (válido)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "nome": "João Silva",
        "email": "joao.silva@email.com",
        "senha": "123456"
    }'
    
    # Criar usuário (válido)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "nome": "Gui",
        "email": "gui@gmail.com",
        "senha": "123456"
    }'
    
    # Criar usuário (inválido - e-mail já cadastrado)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "nome": "Gui",
        "email": "joao.silva@email.com",
        "senha": "123456"
    }'

## LISTAR
    
    # Listar usuários (GET - válido)
    curl -X GET "http://localhost/restaurante/back/api/usuario.php"
    
    # Listar usuários com parâmetro
    curl -X GET "http://localhost/restaurante/back/api/usuario.php?id=1"
    curl -X GET "http://localhost/restaurante/back/api/usuario.php?ativo=false"
    curl -X GET "http://localhost/restaurante/back/api/usuario.php?email=gui@email.com"

## EDITAR
    
    # Editar usuário (válido)
    curl -X PUT "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "id": 1,
        "nome": "João Silva Atualizado",
        "email": "joao.silva.atualizado@email.com"
    }'
    
    # Editar usuário (inválido - sem id)
    curl -X PUT "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "nome": "João",
        "senha": "123456"
    }'
## DELETAR
    
    # Deletar usuário (válido)
    echo "Deletar usuário (válido)"
    curl -X DELETE "http://localhost/restaurante/back/api/usuario.php?id=2"
    
    # Deletar usuário (inválido - ID não encontrado)
    curl -X DELETE "http://localhost/restaurante/back/api/usuario.php?id=999"

## LOGIN

    # Login com dados (válido)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "login": true,
        "email": "gui@gmail.com",
        "senha": "123456"
    }'

    # Login com dados (inválido - senha incorreta)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "login": true,
        "email": "gui@email.com",
        "senha": "senhaerrada"
    }'

    # Login com token (válido)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "login": true,
        "token": "c5fe6e39f403038bbb39a3d7ea6b6cdcfa7eceb831d522b10cbad7f8ca39e8fe"
    }'

    # Login com token (inválido)
    curl -X POST "http://localhost/restaurante/back/api/usuario.php" -H "Content-Type: application/json" -d '{
        "login": true,
        "token": "token_invalido"
    }'

## LOGOUT

    # Logout (válido)
    curl -X DELETE "http://localhost/restaurante/back/api/usuario.php?token=2aa0dd24c1348cb2a1db626107f8111e8a824a7dbbbb44384c08cdaba0fd7cb8"

    # Logout (inválido - token não encontrado)
    curl -X DELETE "http://localhost/restaurante/back/api/usuario.php?token=token_invalido"